### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by rripken** [jalajthanaki/DataScience_Interview_Seminar#1]
You have some typos you should fix.
 perameter, continous, robost, ensamble, sgmentation

**Comment by jalajthanaki** [comment]
Thanks for raising this issue. I will upload the updated version in upcoming days.

**Comment by jalajthanaki** [comment]
Hi Ryan Ripken @rripken,

Thank you for your kind attention and putting this into my notice. 
I have fixed this issue. You can see the changes using [this link](https://raw.githubusercontent.com/jalajthanaki/DataScience_Interview_Seminar/master/imgs/ML_Algorithm_Cheat_Shee_Revised.png)
